### ISSUE TITLE
PHP requirement update

### ISSUE THREAD

**Issue by broakenmedia** [Cyber-Duck/laravel-test#5]
Hi! I think there's a small inconsitency in the docs:

https://github.com/Cyber-Duck/laravel-test/blob/main/docs/01-local-development-setup.md

Mentions that PHP 8.1 is required however it looks like the update to Laravel 10 moved the requirement to 8.2 (despite 10 still supporting 8.1) and giving myriad composer errors. No big deal, i just updated local to 8.2 and contiuned but thought i should point it out. 🙂

![image](https://github.com/Cyber-Duck/laravel-test/assets/1523918/2299c426-4a7a-4ea9-86d3-24f5e20b1c22)

Apologies if i've missed some good reason for this!

**Comment by worzy** [comment]
@broakenmedia Good observation.  We'll get that updated.

**Comment by gdrew8** [comment]
Fixed in https://github.com/Cyber-Duck/laravel-test/pull/6
